### ISSUE TITLE
实现用于比赛的`submit`分支

### ISSUE THREAD

**Issue by Cai1Hsu** [neuq-rcore/rCore#17]
# TODOs

### Repo management
- [x] Add test suits
- [x] Add test script and CI
- [x] Modify `Makefile` so that it compiles and produces `kernel-qemu` and `sbi-qemu`
- [x] #24

### Kernel design
- [x] #18
- [x] #19
- [x] #20
- [x] #21
- [x] #22
- [x] #23

**Comment by Cai1Hsu** [comment]
初赛目标已完成
![IMG_20240527_232605](https://github.com/neuq-rcore/rCore/assets/47081443/5e7fb99d-4597-44ca-bd03-3745fe052ffb)
